### ISSUE TITLE
Belated airspace comment causes error

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#475]
Upload Flight w violation > Go to Profile > My flights > open flight > edit airspace comment > save > error

Error is caused, because no glider was added by the previous upload dialog.

Should we store the flight w the default glider of the user? Or how should be handle this? @JEK58

**Comment by JEK58** [comment]
From UX perspective the user should not get the airspace violation mail because he is still in the form and has not submitted the flight yet. Maybe he decides to not upload the flight after all. Also in the admin panel the flight should only be visible when the user submitted the flight. 

This is what I actually was expecting to be the current way. 
By doing so the missing glider problem is gone and UX is way better.

Only if the Leonardo interface is used the user should get a mail with call to action regarding airspace comment. There the default glider is used automatically so there should be no problem editing the flight.
